#include <stdio.h>

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// 
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.


int main() {
  unsigned long x_1, x_2, sum, new_x_2;
  x_1 = 1;
  x_2 = 1;
  sum = 0;
  new_x_2;
  
  while (x_2 <= 4000000) {
    if (x_2 % 2 == 0) {
      sum += x_2;
    }
    new_x_2 = x_1 + x_2;
    x_1 = x_2;
    x_2 = new_x_2;
  }
  printf("SUM: %lu\n", sum);
}